### ISSUE TITLE
marina.signTransaction: support passing both psetv0 and v2

### ISSUE THREAD

**Issue by tiero** [vulpemventures/marina#400]
try/catch with Psbt an Pset classes, before returning error to user

**Comment by Randy808** [comment]
Is this still something on the roadmap?
<img width="359" alt="screenshot" src="https://github.com/vulpemventures/marina/assets/4742100/e59523c6-b215-4a19-90f3-46af2944827d">

**Comment by tiero** [comment]
this seems to be the Transaction Version, not PSET/PSBT in particular. A reason to not use version 2?

**Comment by Randy808** [comment]
Sorry for the late response but here's the full context:

After the marina api change I tried to make a shim wrapper around the utxos returned from 'marina.getCoins()' to match the old format. It seemed to work okay until I serialized the Ps***b***t (the class for pset v1) and sent it to marina for signing. This is what it looks like before serialization via 'pset.toBase64()':

<img width="692" alt="Screenshot 2024-01-18 at 2 02 38 PM" src="https://github.com/vulpemventures/marina/assets/4742100/1935e4ce-b365-47cb-8537-bfbd9cafab4d">

I also added the longer base64-encoded psbt in the attached file [here](https://github.com/vulpemventures/marina/files/13980849/psetv1.base64-encoded.txt).

When 'marina.signTransaction' is called it goes to the sign-pset.tsx file and tries to decode the base64 with the Ps***e***t class contained in the liquidjs-lib repo:
https://github.com/vulpemventures/marina/blob/aba89e66d969ed31383bc8a9a15efe86cebf2f05/src/extension/popups/sign-pset.tsx#L127

In the 'fromBase64' method in Pset it calls 'this.fromBuffer':
https://github.com/vulpemventures/liquidjs-lib/blob/69e3e9ee3483000d36c79b9a6cd6ac7a43532872/src/psetv2/pset.js#L72

And in the 'fromBuffer' method it calls 'sanityCheck' after failing to decode a KeyPair:
https://github.com/vulpemventures/liquidjs-lib/blob/69e3e9ee3483000d36c79b9a6cd6ac7a43532872/src/psetv2/globals.js#L43

And in the sanity check, the error about the txVersion always gets called:
https://github.com/vulpemventures/liquidjs-lib/blob/69e3e9ee3483000d36c79b9a6cd6ac7a43532872/src/psetv2/globals.js#L153

I assume this is stemming from a difference in parsing between psetv1 and psetv2.

Either way this will always get hit whenever we're in the first 'catch' of 'fromBuffer' since the PsetGlobal is initialized without any arguments. The error message being incorrect should be addressed in a separate issue though:
https://github.com/vulpemventures/liquidjs-lib/blob/69e3e9ee3483000d36c79b9a6cd6ac7a43532872/src/psetv2/globals.js#L37
