### ISSUE TITLE
getNextAddress() does not show publicKey

### ISSUE THREAD

**Issue by jamesdorfman** [vulpemventures/marina#489]
I am trying to get a raw pubkey from marina (not an address, but the underlying pubkey itself).

The API reference says that `getNextAddress()` should return a publicKey:
<img width="876" alt="Screenshot 2023-08-10 at 4 03 36 PM" src="https://github.com/vulpemventures/marina/assets/6634974/edd8f1a3-7df3-4d78-8500-8575806b86da">

 
However, when I run the following code in google chrome v115
```
await window.marina.enable();
let nextAddr = await window.marina.getNextAddress()
console.log(nextAddr);
```
this is the result which gets logged to the console:
```
{
    confidentialAddress: 'XXX',
    derivationPath: 'XXX',
    accountName: 'mainAccountTest',
    networks: Array(1),
    blindingPrivateKey: 'XXX'
}
```

Is there still a way for me to get a publicKey? Is this a bug?

Thanks!

**Comment by louisinger** [comment]
Hey @jamesdorfman,

indeed, there is an error in the API reference. I'll fix it, thanks! [ docs.vulpem.com/marina/api ](https://docs.vulpem.com/marina/api) should be up to date. 

_About adrress' public key_

 `getNextAddress` returns an [Address](https://github.com/vulpemventures/marina-provider/blob/master/src/types.ts#L46-L51) since `v0.5.x`. The interface does not contain the script public key but you can[ derive it using bip32.](https://gist.github.com/louisinger/0cdd9f7ee3fc2db94e047636ff8d6189)

I close the issue, replaced by https://github.com/vulpemventures/docs.vulpem.com/issues/19

**Comment by stevenroose** [comment]
Do you mean to say that the API call no longer returns an object but just and Address and that's why all other fields were dropped? I think the fields in that screenshot are actually really useful, no? And AFAIU they come for free because internally you already need to have them to construct the address, so returning them has no downsides to me it seems.. Tbf the hardware wallet APIs I've worked with all return the public key alongside the address when deriving or asking for a new address.

**Comment by louisinger** [comment]
> Do you mean to say that the API call no longer returns an object but just and Address and that's why all other fields were dropped? 

No, `Address` is still an interface with all the fields except the public key (+ some additional fields in case of taproot addresses).

> I think the fields in that screenshot are actually really useful, no? And AFAIU they come for free because internally you already need to have them to construct the address, so returning them has no downsides to me it seems.. Tbf the hardware wallet APIs I've worked with all return the public key alongside the address when deriving or asking for a new address.

Yes you're right. Initially we removed the public key because `v0.5.x` introduces account system and returns `masterXPubKey` for each one. So the idea was to remove the "duplicates" and let apps to generate raw public key while they need it. However, you're not the first ones saying this so let's discuss how & if we re-add the public key field there:  https://github.com/vulpemventures/marina-provider/issues/32
